[workspace]
resolver = "2"
members = [
    "server",
    "client",
    "crates/net",
    "crates/platform-api",
    "xtask",
    "crates/minigames/duck_hunt",
    "crates/minigames/null_module",
    "crates/analytics",
]
