[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
sea-orm = { version = "0.12", default-features = false, features = ["sqlx-postgres", "runtime-tokio-rustls", "macros"] }
anyhow = "1"
