[package]
name = "analytics"
version = "0.1.0"
edition = "2024"

[dependencies]
prometheus = "0.13"
opentelemetry = { version = "0.22", features = ["metrics"] }
reqwest = { version = "0.11", features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt", "macros"] }
