name = "duck_range_01"
background = "sky.png"

[[ducks]]
path = [[-5.0, 1.0, 0.0], [5.0, 1.5, 0.0]]
speed = 5.0

[[ducks]]
path = [[5.0, 1.0, 0.0], [-5.0, 2.0, 0.0]]
speed = 4.0

[weapon]
max_ammo = 6
reload_time = 2.0

[hud]
font = "fonts/FiraSans-Bold.ttf"
font_size = 32.0
color = "#ffffff"
