[package]
name = "physics"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.12", default-features = false, features = ["bevy_render"] }
bevy_rapier3d = { version = "0.24", default-features = false, features = ["dim3"] }
